theme: minima
title: Flagg Visual Computing LLC 
description: A computer vision and graphics consultancy

header_pages:
  - about.md
  - portfolio.md

author:
  name             : "Matt Flagg"
  avatar           : "yo.jpg"
  bio              : "Consultant"
  location         : "Saint Simons Island, GA"
  googlescholar    : "https://scholar.google.com/citations?user=SvuSifMAAAAJ&hl=en"
  email            : "mflagg@gmail.com"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : 
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "https://www.linkedin.com/in/matt-flagg-47a4643/"
  pinterest        :
  soundcloud       :
  steam            :
  tumblr           :
  twitter          : "mattflagg"
  vine             :
  weibo            :
  xing             :
  youtube          : 
  wikipedia        :


